name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: eu-north-1
      AWS_REGION: eu-north-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build and push Docker Image
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker build -t my-node-app .
          docker tag my-node-app:latest joshuaveeraiah/my-node-app:latest
          docker push joshuaveeraiah/my-node-app:latest

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform Deployment
        run: terraform plan

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve

      - name: Get ECS Service ARN
        id:   get_service_arn
        run: |
            echo "service_arn=$(terraform output ecs_service_arn)" >> $GITHUB_ENV

      - name: Update ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          family: hello-world-task
          task-definition: ${{ steps.get_service_arn.outputs.service_arn }}
          container-image-name: joshuaveeraiah/my-node-app:latest
          service: "hello-world-service"
          cluster: "arn:aws:ecs:eu-north-1:058264184150:cluster/hello-world-cluster"
          wait-for-service-stability: 'true'
      - name: Deploy to ECS
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
            echo "Deploying to ECS"
            ecs-cli compose --file docker-compose.yml --project-name hello-world-node service up
